---
- name: set permissions on system bash_completion.d directory
  file:
    state: directory
    path: "/etc/bash_completion.d"
    owner: "{{ target_user }}"
    group: "{{ target_group }}"
    mode: 0755
    setype: etc_t
    seuser: system_u

- name: push bashrc and profile
  copy:
    src: "{{ item }}"
    dest: "{{ user_dir_home }}/.{{ item }}"
    mode: 0400
    owner: "{{ target_user }}"
    group: "{{ target_group }}"
    setype: config_home_t
    seuser: system_u
  loop:
    - bashrc
    - profile
