version: "3.3"

services:
  librarian:
    image: lscr.io/linuxserver/lazylibrarian
    environment:
      - PUID=1000
      - PGID=100
      - "TZ=Australia/Adelaide"
      - DOCKER_MODS=linuxserver/mods:lazylibrarian-ffmpeg
    volumes:
      - librarian_service_config_volume:/config
      - storage_books:/books
      - storage_downloads:/downloads
    restart: unless-stopped
    labels:
      traefik.http.routers.librarian-ui-router.service: librarian-ui-service
      traefik.http.routers.librarian-ui-router.rule: Host(`librarian.home.lan`)
      traefik.http.services.librarian-ui-service.loadbalancer.server.port: 5299
      plugsy.name: "Lazylibrarian"
      plugsy.category: "Media"
      plugsy.icon: "@styled-icons/material-twotone/LocalLibrary"

volumes:
  librarian_service_config_volume:
  storage_books:
    external: true
  storage_downloads:
    external: true

networks:
  default:
    external:
      name: traefik_proxy
