---
dependencies:
    - role: gantsign.visual-studio-code
      users:
          - username: "{{ target_user }}"
            visual_studio_code_extensions:
              - streetsidesoftware.code-spell-checker
              - wholroyd.jinja
              - ms-python.python
