---
- name: assert supported distribution
  assert:
    that:
      - "ansible_pkg_mgr in ('apt', 'yum', 'dnf', 'zypper', 'homebrew')"

- name: 'install ({{ ansible_pkg_mgr }})'
  include_tasks: 'setup-{{ ansible_pkg_mgr }}.yml'

- include_tasks: user-{{ ansible_pkg_mgr }}.yml
- include_tasks: packages-{{ ansible_pkg_mgr }}.yml
