---
- name: install base packages
  package:
    state: present
    name:
      - ansible
      - yamllint
      - google-roboto-slab-fonts
      - htop
      - jq
      - powerline-fonts
      - youtube-dl
