---
galaxy_info:
  role_name: airtonix.provisioning/system/base
  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
    - name: Debian
      versions:
        - 10
    - name: Fedora
      versions:
        - all
    - name: Macosx
      versions:
        - all

  galaxy_tags:
    - linux

dependencies:
  - role: mhutter.docker-systemd-service
