---
- name: install vim
  package:
    state: present
    name: vim

- name: create vim user config directories
  file:
    state: directory
    path: "{{ user_dir_home }}/{{ item }}"
    mode: 0700
    owner: "{{ target_user }}"
    group: "{{ target_group }}"
    seuser: system_u
  loop:
    - .vim
    - .vim/autoload
    - .vim/bundle

- name: push vimrc
  copy:
    src: "{{ role_path }}/files/vimrc"
    dest: "{{ user_dir_home }}/.vimrc"
    mode: 0400
    owner: "{{ target_user }}"
    group: "{{ target_group }}"
    setype: user_home_t
    seuser: system_u

- name: configure vim - pathogen
  get_url:
    url: "https://tpo.pe/pathogen.vim"
    dest: "{{ user_dir_home }}/.vim/autoload/pathogen.vim"
    mode: 0600
    owner: "{{ target_user }}"
    group: "{{ target_group }}"
    seuser: system_u

- name: add vim plugin - black
  become: true
  become_user: "{{ target_user }}"
  git:
    repo: "https://github.com/psf/black.git"
    dest: "{{ user_dir_home }}/.vim/bundle/black"
    version: stable
    accept_hostkey: yes

- name: add vim plugin - code_complete
  become: true
  become_user: "{{ target_user }}"
  git:
    repo: "https://github.com/mbbill/code_complete.git"
    dest: "{{ user_dir_home }}/.vim/bundle/vim-code-complete"
    accept_hostkey: yes

- name: add vim plugin - Dockerfile.vim
  become: true
  become_user: "{{ target_user }}"
  git:
    repo: "https://github.com/ekalinin/Dockerfile.vim.git"
    dest: "{{ user_dir_home }}/.vim/bundle/vim-dockerfile"
    accept_hostkey: yes

- name: add vim plugin - salt-vim
  become: true
  become_user: "{{ target_user }}"
  git:
    repo: "https://github.com/saltstack/salt-vim.git"
    dest: "{{ user_dir_home }}/.vim/bundle/salt-vim"
    accept_hostkey: yes

- name: add vim plugin - syntastic
  become: true
  become_user: "{{ target_user }}"
  git:
    repo: "https://github.com/vim-syntastic/syntastic.git"
    dest: "{{ user_dir_home }}/.vim/bundle/vim-syntastic"
    accept_hostkey: yes

- name: add vim plugin - vim-airline
  become: true
  become_user: "{{ target_user }}"
  git:
    repo: "https://github.com/vim-airline/vim-airline.git"
    dest: "{{ user_dir_home }}/.vim/bundle/vim-airline"
    accept_hostkey: yes

- name: add vim plugin - vim-closetag
  become: true
  become_user: "{{ target_user }}"
  git:
    repo: "https://github.com/alvan/vim-closetag.git"
    dest: "{{ user_dir_home }}/.vim/bundle/vim-closetag"
    accept_hostkey: yes

- name: add vim plugin - vim-flake8
  become: true
  become_user: "{{ target_user }}"
  git:
    repo: "https://github.com/nvie/vim-flake8.git"
    dest: "{{ user_dir_home }}/.vim/bundle/vim-flake8"
    accept_hostkey: yes

- name: add vim plugin - vim-jinja
  become: true
  become_user: "{{ target_user }}"
  git:
    repo: "https://github.com/mitsuhiko/vim-jinja.git"
    dest: "{{ user_dir_home }}/.vim/bundle/vim-jinja"
    accept_hostkey: yes

- name: add vim plugin - vim-snippets
  become: true
  become_user: "{{ target_user }}"
  git:
    repo: "https://github.com/honza/vim-snippets.git"
    dest: "{{ user_dir_home }}/.vim/bundle/vim-snippets"
    accept_hostkey: yes

- name: add vim plugin - vim-surround
  become: true
  become_user: "{{ target_user }}"
  git:
    repo: "https://github.com/tpope/vim-surround.git"
    dest: "{{ user_dir_home }}/.vim/bundle/vim-surround"
    accept_hostkey: yes
