version: "3.3"

services:
  codeserver:
    image: lscr.io/linuxserver/code-server
    restart: unless-stopped
    expose:
      - 8443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - SUDO_PASSWORD=password #optional
      - PROXY_DOMAIN=codeserver.home.lan #optional
      - DEFAULT_WORKSPACE=/home/coder/projects
      - DOCKER_MODS=linuxserver/mods:code-server-docker
    labels:
      traefik.http.routers.codeserver-ui-router.service: codeserver-ui-service
      traefik.http.routers.codeserver-ui-router.rule: Host(`codeserver.home.lan`)
      traefik.http.services.codeserver-ui-service.loadbalancer.server.port: 8443
    volumes:
      - codeserver_service_data_volume:/config
      - debrid_data:/home/coder/projects/debrid
      - nodered_data:/home/coder/projects/nodered
      - jellyfin_data:/home/coder/projects/jellyfin
      - portainer_data:/home/coder/projects/portainer
      - /srv/dev-disk-by-uuid-45a8637d-14c5-448d-bfba-7c722c1b84ea/services/Homer/assets:/home/coder/projects/homer
      - /var/run/docker.sock:/var/run/docker.sock:rw


volumes:
  codeserver_service_data_volume:
  debrid_data:
    external:
      name: debrid_debrid_service_data_volume
  nodered_data:
    external:
      name: nodered_nodered_service_data_volume
  portainer_data:
    external:
      name: portainer_portainer_service_data_volume
  jellyfin_data:
    external:
      name: jellyfin_jellfin_service_config_volume

networks:
  default:
    external:
      name: traefik_proxy
