version: "3.3"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      # - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    labels:
      traefik.http.routers.jellyfin-router.service: jellyfin-service
      traefik.http.routers.jellyfin-router.rule: Host(`jellyfin.home.lan`)
      traefik.http.services.jellyfin-service.loadbalancer.server.port: 8096
      traefik.tcp.routers.jellyfin-router.service: jellyfin-service
      traefik.tcp.routers.jellyfin-router.rule: Host(`jellyfin.home.lan`)
      traefik.tcp.services.jellyfin-service.loadbalancer.server.port: 8096
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional: advertise to local jellyfin network clients
      - 1900:1900/udp #optional: advertise to local dlna network clients
    # devices:
    #   - /dev/dri:/dev/dri #optional
    #   - /dev/vcsm:/dev/vcsm #optional
    #   - /dev/vchiq:/dev/vchiq #optional
    #   - /dev/video10:/dev/video10 #optional
    #   - /dev/video11:/dev/video11 #optional
    #   - /dev/video12:/dev/video12 #optional
    #   - 1900:1900/udp #optional
    volumes:
      - jellfin_service_config_volume:/config
      - /srv/dev-disk-by-uuid-45a8637d-14c5-448d-bfba-7c722c1b84ea/store/Videos/Movies:/data/movies
      - /srv/dev-disk-by-uuid-45a8637d-14c5-448d-bfba-7c722c1b84ea/store/Videos/Tv:/data/tvshows

volumes:
  jellfin_service_config_volume:

networks:
  default:
    external:
      name: traefik_proxy
