version: "3.3"

services:
  codeserver:
    image: ghcr.io/linuxserver/code-server@sha256:fd64244ce0fe8289da3778713384e68f011487113bf1852f1de5b120fba34b26
    restart: unless-stopped
    expose:
      - 8443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - SUDO_PASSWORD=password #optional
      - PROXY_DOMAIN=codeserver.home.lan #optional
      - DEFAULT_WORKSPACE=/home/coder/projects
      - DOCKER_MODS=linuxserver/mods:code-server-docker
    labels:
      traefik.http.routers.codeserver-ui-router.service: codeserver-ui-service
      traefik.http.routers.codeserver-ui-router.rule: Host(`codeserver.home.lan`)
      traefik.http.services.codeserver-ui-service.loadbalancer.server.port: 8443
      plugsy.name: "VSCode"
      plugsy.category: "Storage"
      plugsy.icon: "@styled-icons/material-twotone/Code"
      plugsy.link: http://codeserver.home.lan
    volumes:
      - codeserver_service_data_volume:/config
      - debrid_data:/home/coder/projects/debrid
      - nodered_data:/home/coder/projects/nodered
      - jellyfin_data:/home/coder/projects/jellyfin
      - /srv/dev-disk-by-uuid-45a8637d-14c5-448d-bfba-7c722c1b84ea/services/HomeAsssistant:/home/coder/projects/homeassistant
      - /var/run/docker.sock:/var/run/docker.sock:rw

volumes:
  codeserver_service_data_volume:
  debrid_data:
    external:
      name: debrid_debrid_service_data_volume
  nodered_data:
    external:
      name: nodered_nodered_service_data_volume
  portainer_data:
    external:
      name: portainer_portainer_service_data_volume
  jellyfin_data:
    external:
      # yes incorrect spelling is due to jeyllyfin docker compose setup (lmao)
      name: jellyfin_jellfin_service_config_volume
  homeassistant_data:
    external:
      name: homeassistant_homeassistant_service_data_volume

networks:
  default:
    external:
      name: traefik_proxy
