version: "3.3"

services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web@sha256:f835a332cbf22d478bef41f1dd698cc737f2f4458c8df688ed1194c40428b274
    environment:
      - PUID=1000
      - PGID=100
      - "TZ=Australia/Adelaide"
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - calibreweb_service_config_volume:/config
      - storage_books:/books
    restart: unless-stopped
    labels:
      traefik.http.routers.calibreweb-ui-router.service: calibreweb-ui-service
      traefik.http.routers.calibreweb-ui-router.rule: Host(`books.home.lan`)
      traefik.http.services.calibreweb-ui-service.loadbalancer.server.port: 8083
      plugsy.name: "Calibre"
      plugsy.category: "Media"
      plugsy.icon: "@styled-icons/material-twotone/MenuBook"
      plugsy.link: http://books.home.lan


  calibre:
    image: ghcr.io/linuxserver/calibre@sha256:641408f3eed99f8acf4c2e448591c67881b26f4123decb526214adc03a5c635e
    environment:
      - PUID=1000
      - PGID=100
      - "TZ=Australia/Adelaide"
      - PASSWORD=password #optional
      # - CLI_ARGS= #optional
      # - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
    volumes:
      - calibre_service_config_volume:/config
      - storage_books:/books
    restart: unless-stopped
    labels:
      traefik.http.routers.calibre-router.service: calibre-service
      traefik.http.routers.calibre-router.rule: Host(`calibre.home.lan`)
      traefik.http.services.calibre-service.loadbalancer.server.port: 8081
      traefik.http.routers.calibre-desktop-router.service: calibre-desktop-service
      traefik.http.routers.calibre-desktop-router.rule: Host(`calibredesktop.home.lan`)
      traefik.http.services.calibre-desktop-service.loadbalancer.server.port: 8080
      plugsy.name: "CalibreServer"
      plugsy.parents: "Calibre"
      plugsy.icon: "@styled-icons/feather/Server"

volumes:
  calibre_service_config_volume:
  calibreweb_service_config_volume:
  storage_books:
    external: true

networks:
  default:
    external:
      name: traefik_proxy
