---
- name: Install MkDkr
  get_url:
    url: https://raw.githubusercontent.com/rosineygp/mkdkr/master/.mkdkr
    dest: "{{ user_dir_applications }}/mkdkr"

- name: Link MkDkr
  file:
    src: "{{ user_dir_applications }}/mkdkr"
    path: "{{ user_dir_home }}/.mkdkr"
    owner: "{{ target_user }}"
    group: "{{ target_group }}"
    state: link
