---
- name: Create Traefik Network
  docker_network:
    name: traefik_proxy
    state: present
    internal: false

- name: Traefik Unitfile
  include_role:
    name: airtonix.systemd/dockercompose
  vars:
    app_name: traefik-compose-service
    compose_source: files/
    compose_workdir: /srv/dev-disk-by-uuid-45a8637d-14c5-448d-bfba-7c722c1b84ea/services/Traefik
