---
- name: Traefik Config Store
  ansible.builtin.file:
    path: /yacht/AppData/Config/Traefik/config
    state: directory
    mode: '0755'

- name: Traefik Unitfile
  include_role:
    name: kibatic.docker-systemd
  vars:
    systemd_units:
      - name: traefik
        restart_unit: true
        host_copy: []
        image: traefik:v2.5
        ports:
          - '80:80'
          - '8080:8080'
        labels:
          - 'traefik.http.routers.traefik-ui-router.service=traefik-ui-service'
          - 'traefik.http.routers.traefik-ui-router.rule=Host(`traefik.home.lan`)'
          - 'traefik.http.services.traefik-ui-service.loadbalancer.server.port=8080'
        volumes:
          - '/var/run/docker.sock:/var/run/docker.sock:rw'
        command: --api.insecure=true --providers.docker
