version: "3.3"

services:
  youtube-dl:
    image: b4bz/homer
    volumes:
      - /srv/dev-disk-by-uuid-45a8637d-14c5-448d-bfba-7c722c1b84ea/store/Homer:/www/assets
    restart: unless-stopped
    labels:
      traefik.http.routers.homer-ui-router.service: homer-ui-service
      traefik.http.routers.homer-ui-router.rule: Host(`dashboard.home.lan`)
      traefik.http.services.homer-ui-service.loadbalancer.server.port: 8080

networks:
  default:
    external:
      name: traefik_proxy
