---
- name: Install Tusk
  shell: >
    curl -sL https://git.io/tusk | sh -s -- -b ~/bin latest
  args:
    executable: /bin/bash
    chdir: "{{ user_home_dir }}"
    creates: "{{ user_home_dir }}/bin/tusk"
