version: "3.3"

services:
  notea:
    image: cinwell/notea
    restart: unless-stopped
    expose:
      - 3000
    environment:
      - STORE_ACCESS_KEY=noteaak
      - STORE_SECRET_KEY=noteask
      - STORE_BUCKET=notea
      - STORE_END_POINT=http://minio:9000
      - STORE_FORCE_PATH_STYLE=true
      - PASSWORD=totallymypassword
    labels:
      traefik.http.routers.notea-ui-router.service: notea-ui-service
      traefik.http.routers.notea-ui-router.rule: Host(`notes.home.lan`)
      traefik.http.services.notea-ui-service.loadbalancer.server.port: 3000

  minio:
    image: minio/minio
    labels:
      traefik.enable: true
      traefik.http.routers.notea-minio-router.service: notea-minio-service
      traefik.http.routers.notea-minio-router.rule: Host(`minio.home.lan`)
      traefik.http.services.notea-minio-service.loadbalancer.server.port: 9000
      traefik.http.routers.notea-minio-console-router.service: notea-minio-console-service
      traefik.http.routers.notea-minio-console-router.rule: Host(`minio-console.home.lan`)
      traefik.http.services.notea-minio-console-service.loadbalancer.server.port: 9001
    volumes:
      - notea_minio_service_data_volume:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=totallymypassword
    command: 'server /data --console-address "minio-console.home.lan"'

volumes:
  notea_minio_service_data_volume:


networks:
  default:
    external:
      name: traefik_proxy
