version: "3.3"

services:
  nodered:
    image: nodered/node-red:3.0.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - nodered_service_data_volume:/data
    group_add:
      - 993
    labels:
      traefik.http.routers.nodered-ui-router.service: nodered-ui-service
      traefik.http.routers.nodered-ui-router.rule: Host(`nodered.home.lan`)
      traefik.http.services.nodered-ui-service.loadbalancer.server.port: 1880
      plugsy.name: "NodeRef"
      plugsy.category: "Automation"
      plugsy.icon: "@styled-icons/material-twotone/Cable"
      plugsy.link: http://nodered.home.lan

volumes:
  nodered_service_data_volume:

networks:
  default:
    external:
      name: traefik_proxy
