---
- name: Install ShellSpec
  shell: >
    curl -fsSL https://git.io/shellspec | sh
  args:
    executable: /bin/bash
    chdir: "{{ user_home_dir }}"
    creates: "{{ user_home_dir }}/.local/lib/shellspec"
