---
- name: Install ShellSpec
  shell: >
      curl -fsSL https://git.io/shellspec | sh
  args:
    executable: /bin/bash
    chdir: "{{ usr_home_dir }}"
    creates: "{{ euser_home_dir }}/.local/lib/shellspec"
