---
- name: add new groups - docker, libvirt
  group: name={{ item }}
  loop:
    - docker

- name: add target user to new groups
  user:
    name: "{{ target_user }}"
    groups: docker
    append: true

- name: Install docker-compose
  package:
    state: present
    name:
      - docker-compose
