---
# tasks file for syncthing
- name: install syncthing (distribution:Fedora)
  package:
    state: present
    name: syncthing
  when: ansible_facts['distribution'] == "Fedora"

- name: start/enable syncthing.service by user service manager
  service:
    name: syncthing.service
    user: yes
    state: started
    enabled: yes
