---
- name: Install go-task
  shell: >
    sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
  args:
    executable: /bin/bash
    chdir: "{{ user_dir_home }}"
    creates: "{{ user_dir_home }}/.local/bin/task"
