version: "3.3"

services:
  jackett:
    image: ghcr.io/linuxserver/jackett@sha256:fca4164aa85069d23b7b6fe058915284f35f345f91ad166991210d9e97bfde9e
    dns:
      - "192.168.8.149"
    dns_search: home.lan
    environment:
      - PUID=1000
      - PGID=100
      - "TZ=Australia/Adelaide"
      - AUTO_UPDATE=true
    volumes:
      - jackett_service_config_volume:/config
      - storage_downloads:/downloads
    restart: unless-stopped
    labels:
      traefik.http.routers.jackett-ui-router.service: jackett-ui-service
      traefik.http.routers.jackett-ui-router.rule: Host(`jackett.home.lan`)
      traefik.http.services.jackett-ui-service.loadbalancer.server.port: 9117
      plugsy.name: "Jackett"
      plugsy.category: "Media"
      plugsy.icon: "@styled-icons/material-twotone/QueryStats"
      plugsy.link: http://jackett.home.lan

volumes:
  jackett_service_config_volume:
  storage_downloads:
    external: true

networks:
  default:
    external:
      name: traefik_proxy
