---
- name: Install Volta
  shell: |
    curl https://get.volta.sh | bash -s -- --skip-setup
  args:
    executable: /bin/bash
    chdir: "{{ user_dir_home }}"
    creates: "{{ user_dir_home }}/.volta/bin"

- name: Install Node@LTS
  shell: |
    volta install node
  args:
    executable: /bin/bash
    chdir: "{{ user_dir_home }}"
    creates: "{{ user_dir_home }}/.volta/bin"
