version: "3.3"

services:
  samba:
    image: dperson/samba
    restart: unless-stopped
    environment:
      TZ: 'Australia/Adelaide'
      USERID: "1000"
      GROUPID: "1000"
    stdin_open: true
    tty: true

    command: >
      -s "homes;/mnt/homes;yes;no;yes"
      -s "torrents;/mnt/torrents;yes;no;yes"
      -s "movies;/mnt/movies;yes;no;yes"
      -s "tv;/mnt/tv;yes;no;yes"
      -s "audio;/mnt/audio;yes;no;yes"
      -s "books;/mnt/books;yes;no;yes"
      -s "audiobooks;/mnt/audiobooks;yes;no;yes"
      -s "reference;/mnt/reference;yes;no;yes"
      -n
      -w "LAN"
      -p
      -g "netbios name = HOME"
      -g "netbios aliases = HOME"
      -g "remote announce = 192.168.8.255"

    network_mode: host
    volumes:
      - storage_torrents:/mnt/torrents
      - storage_movies:/mnt/movies
      - storage_tv:/mnt/tv
      - storage_books:/mnt/books
      - storage_audio:/mnt/audio
      - storage_audiobooks:/mnt/audiobooks
      - storage_reference:/mnt/reference
      - storage_homes:/mnt/homes

volumes:
  storage_torrents:
    external: true
  storage_movies:
    external: true
  storage_tv:
    external: true
  storage_books:
    external: true
  storage_audio:
    external: true
  storage_audiobooks:
    external: true
  storage_reference:
    external: true
  storage_homes:
    external: true
