---
- debug:
    msg: "{{ hostvars[inventory_hostname].ansible_distribution }}@{{ hostvars[inventory_hostname].ansible_distribution_version }}"

- name: assert supported distribution
  assert:
    that:
      - "ansible_pkg_mgr in ('apt', 'yum', 'dnf', 'zypper', 'homebrew')"

- name: 'install ({{ ansible_pkg_mgr }})'
  include_tasks: 'main-{{ ansible_pkg_mgr }}.yml'
