---

- name: add target user
  user:
    name: "{{ target_user }}"
    comment: "{{ target_user_name }}"
    groups: wheel
    append: yes
    generate_ssh_key: yes
    ssh_key_file: ".ssh/id_ed25519"
    ssh_key_type: ed25519

- name: create misc. workspace directories
  file:
    state: directory
    path: "{{ user_dir_home }}/{{ item }}"
    group: "{{ target_group }}"
    owner: "{{ target_user }}"
    mode: 0700
    seuser: system_u
  loop:
    - .ansible/tmp
    - Projects
    - Applications
    - bin
