---
- name: NodeRed Unitfile
  include_role:
    name: mhutter.docker-systemd-service
  vars:
    container_name: nodered
    container_image: nodered/node-red:latest
    container_volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'portainer_data:/data'
      - '/data'
    container_ports:
      - '8000:8000'
      - '9000:9000'
      - '9443:9443'
    container_labels:
      - 'traefik.http.routers.portainer-ui-router.service=portainer-ui-service'
      - 'traefik.http.routers.portainer-ui-router.rule=Host(`portainer.home.lan`)'
      - 'traefik.http.services.portainer-ui-service.loadbalancer.server.port=8000'
