---
- name: Install requirements (Roles)
  command: |
    ansible-galaxy install \
      -r {{ role_path }}/requirements.yml

- name: Install requirements (Collections)
  command: |
    ansible-galaxy collection install \
      -r {{ role_path }}/requirements.yml
