---
- name: Ensure Homebrew directory exists.
  file:
    path: "{{ homebrew_install_path }}"
    state: directory
    mode: 0775

- name: Ensure Bin directory exists.
  file:
    path: "{{ homebrew_bin_path }}"
    state: directory
    mode: 0775

- name: Ensure Homebrew is installed.
  git:
    repo: "{{ homebrew_repo }}"
    version: master
    dest: "{{ homebrew_install_path }}"
    update: false
    depth: 1

- name: Check if homebrew binary is already in place.
  stat: "path={{ homebrew_bin_path }}/brew"
  register: homebrew_binary
  check_mode: false

- name: Setup Homebrew binary
  when: not homebrew_binary.stat.exists
  block:
    - name: Symlink brew to homebrew_bin_path.
      file:
        src: "{{ homebrew_install_path }}/bin/brew"
        dest: "{{ homebrew_bin_path }}/brew"
        state: link
    - name: Force update brew after installation.
      command: "{{ homebrew_bin_path }}/brew update --force"
