---

- name: Make sure Homebrew directories exists
  become: true
  file:
    path: /usr/local/*
    state: directory
    mode: 0775
    owner: root
    group: wheel
    recurse: true

- name: Download Homebrew installation script
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/master/install
    dest: /tmp/install

- name: Install Homebrew
  shell: /usr/bin/ruby /tmp/install < /dev/null

- name: Set permissions for /usr/local/*
  become: true
  with_items: '{{ homebrew_paths }}'
  ignore_errors: true
  file:
    path: '{{ item }}'
    mode: '0775'
    owner: '{{ username }}'
    group: wheel
    recurse: true
    state: directory

- name: Fix ACL permissions for multiple users
  become: true
  args:
    warn: false
  with_items: '{{ homebrew_paths }}'
  ignore_errors: true
  command: >
    chmod -R +a "group:admin allow list,add_file,search,delete,add_subdirectory,delete_child,readattr,writeattr,readextattr,writeextattr,readsecurity,file_inherit,directory_inherit" {{ item }}


- name: Reset the Homebrew Library repo
  git:
    repo=https://github.com/Homebrew/brew.git
    dest=/usr/local/Homebrew/Library
    clone=no
    update=yes
    force=yes

- name: Update Homebrew (first try may fail)
  homebrew: update_homebrew=yes
  become: false
  ignore_errors: true

- name: Update Homebrew
  homebrew: update_homebrew=yes
  become: false
