---
- name: install/upgrade git
  become: false
  package:
    state: present
    name: git

- name: push git user config files
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    mode: 0400
  loop:
    - .gitconfig
