---
- name: install/upgrade git
  become: false
  package:
    state: present
    name: git

- name: push git user config files
  copy:
    src: "{{ item }}"
    dest: "/home/{{ ansible_user }}/.{{ item }}"
    mode: 0400
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    seuser: system_u
  loop:
    - gitconfig
