version: "3.3"

services:
  metube-dl:
    image: alexta69/metube
    restart: unless-stopped
    expose:
      - 8081
    volumes:
      - storage_downloads:/downloads
    labels:
      traefik.http.routers.metube-router.service: metube-service
      traefik.http.routers.metube-router.rule: Host(`metube.home.lan`)
      traefik.http.services.metube-service.loadbalancer.server.port: 8081
      plugsy.name: "MeTube"
      plugsy.category: "Media"
      plugsy.icon: "@styled-icons/material-twotone/CloudDownload"

volumes:
  storage_downloads:
    external: true

networks:
  default:
    external:
      name: traefik_proxy
