---
- name: Samba Unitfile
  include_role:
    name: airtonix.systemd/dockercompose
  vars:
    app_name: samba-compose-service
    create_external_volumes:
      - storage_downloads
      - storage_pictures
      - storage_movies
      - storage_tv
      - storage_books
      - storage_audio
      - storage_audiobooks
      - storage_reference
      - storage_homes
    compose_source: files/
    compose_workdir: /srv/dev-disk-by-uuid-45a8637d-14c5-448d-bfba-7c722c1b84ea/services/Samba
