version: "3.3"

services:
  jackett:
    image: lscr.io/linuxserver/jackett
    environment:
      - PUID=1000
      - PGID=100
      - "TZ=Australia/Adelaide"
      - AUTO_UPDATE=true
    volumes:
      - jackett_service_config_volume:/config
      - storage_downloads:/downloads
    restart: unless-stopped
    labels:
      traefik.http.routers.jackett-ui-router.service: jackett-ui-service
      traefik.http.routers.jackett-ui-router.rule: Host(`jackett.home.lan`)
      traefik.http.services.jackett-ui-service.loadbalancer.server.port: 9117

volumes:
  jackett_service_data_volume:
  storage_downloads:
    external: true

networks:
  default:
    external:
      name: traefik_proxy
