---
- name: Portainer Unitfile
  include_role:
    name: airtonix.systemd/dockercompose
  vars:
    app_name: portainer-compose-service
    compose_source: files/
    compose_workdir: /src/dev-disk-by-uuid-45a8637d-14c5-448d-bfba-7c722c1b84ea/services/Portainer
