---
- name: install zsh
  package:
    state: present
    name: zsh

- name: change user shell to zsh
  become: yes
  user:
    name: "{{ target_user }}"
    shell: /bin/zsh

- name: Ensure Projects.Mine exists
  file:
    path: "{{ user_home_dir }}/Projects/Mine"
    state: directory
    mode: '0755'

- name: clone/update dotfiles
  become: true
  become_user: "{{ target_user }}"
  git:
    repo: git@github.com:airtonix/dotfiles.git
    dest: "{{ user_home_dir }}/Projects/Mine/Dotfiles"
    accept_hostkey: yes
    force: yes
    version: HEAD

- name: push zshenv, zshrc and zprofile
  file:
    state: link
    src: "{{ user_home_dir }}/Projects/Mine/Dotfiles/zsh/.{{ item }}"
    path: "{{ user_home_dir }}/.{{ item }}"
    mode: 0400
    owner: "{{ target_user }}"
    group: "{{ target_group }}"
    setype: config_home_t
    seuser: system_u
  loop:
    - zshrc
    - zshenv
    - zprofile
