version: "3.3"

services:
  readarr:
    image: ghcr.io/linuxserver/readarr:0.1.0-nightly-alpine
    dns:
      - "192.168.8.149"
    dns_search: home.lan
    environment:
      - PUID=1000
      - PGID=100
      - "TZ=Australia/Adelaide"
    volumes:
      - readarr_service_config_volume:/config
      - storage_books:/books
      - storage_downloads:/downloads
    restart: unless-stopped
    labels:
      traefik.http.routers.readarr-ui-router.service: readarr-ui-service
      traefik.http.routers.readarr-ui-router.rule: Host(`readarr.home.lan`)
      traefik.http.services.readarr-ui-service.loadbalancer.server.port: 8787

volumes:
  readarr_service_config_volume:
  storage_books:
    external: true
  storage_downloads:
    external: true

networks:
  default:
    external:
      name: traefik_proxy
