---
- name: Home Automation Server Configuration
  hosts: all
  become: true

  vars:
    os_platform: linux
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - role: airtonix.provisioning/system/base
    - role: airtonix.provisioning/system/python
    - role: airtonix.provisioning/system/docker
      variables:
        docker_storage_root: /srv/dev-disk-by-uuid-45a8637d-14c5-448d-bfba-7c722c1b84ea/docker
    - role: airtonix.provisioning/server/adguard
      tags: [stacks, core, dns, adguard]
    - role: airtonix.provisioning/server/storage
      tags: [stacks, core, storage, samba]
    - role: airtonix.provisioning/server/homer
      tags: [stacks, core, homer, dashboard]
    - role: airtonix.provisioning/server/traefik
      tags: [stacks, core, traefik]
    - role: airtonix.provisioning/server/portainer
      tags: [stacks, core, portainer]
    - role: airtonix.provisioning/server/nodered
      tags: [stacks, automation, nodered]
    - role: airtonix.provisioning/server/homeassistant
      tags: [stacks, automation, homeassistant]
    - role: airtonix.provisioning/server/debrid
      tags: [stacks, media, debrid]
    - role: airtonix.provisioning/server/metube
      tags: [stacks, media, metube]
    - role: airtonix.provisioning/server/duplicati
      tags: [stacks, backup, duplicati]
    - role: airtonix.provisioning/server/codeserver
      tags: [stacks, codeserver]
    - role: airtonix.provisioning/server/calibre
      tags: [stacks, calibre, books]
    - role: airtonix.provisioning/server/mylar
      tags: [stacks, downloading, mylar, books, comics]
    - role: airtonix.provisioning/server/lazylibrarian
      tags: [stacks, downloading, books, lazylibrarian]
    - role: airtonix.provisioning/server/readarr
      tags: [stacks, downloading, books, readarr]
    - role: airtonix.provisioning/server/jackett
      tags: [stacks, downloading, jackett]
