---
- name: Home Automation Server Configuration
  hosts: all
  become: true

  vars:
    os_platform: linux
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - role: airtonix.provisioning/system/base
    - role: airtonix.provisioning/system/python
    - role: airtonix.provisioning/system/docker
    - role: airtonix.provisioning/server/homer
      tags: homer
    - role: airtonix.provisioning/server/traefik
      tags: traefik
    - role: airtonix.provisioning/server/portainer
      tags: portainer
    - role: airtonix.provisioning/server/nodered
      tags: nodered
    - role: airtonix.provisioning/server/homeassistant
      tags: homeassistant
    - role: airtonix.provisioning/server/youtube-dl
      tags: youtube-dl
