---
- name: Home Automation Server Configuration
  hosts: all
  become: true

  vars:
    os_platform: linux
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - role: airtonix.provisioning/system/base
    - role: airtonix.provisioning/system/python
    - role: airtonix.provisioning/system/docker
    - role: airtonix.provisioning/server/homer
      tags: [stacks, homer]
    - role: airtonix.provisioning/server/traefik
      tags: [stacks, traefik]
    - role: airtonix.provisioning/server/portainer
      tags: [stacks, portainer]
    - role: airtonix.provisioning/server/nodered
      tags: [stacks, nodered]
    - role: airtonix.provisioning/server/homeassistant
      tags: [stacks, homeassistant]
    - role: airtonix.provisioning/server/youtube-dl
      tags: [stacks, youtube-dl]
    - role: airtonix.provisioning/server/debrid
      tags: [stacks, debrid]
