---
- name: Fedora Workstation configuration
  hosts: workstation
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3
    target_user: zenobius
    target_group: zenobius
    target_user_name: Zenobius Jiricek
    user_dir_home: "/home/{{ target_user }}"
    user_dir_applications: "{{ user_dir_home }}/Applications"
    user_dir_bin: "{{ user_dir_home }}/bin"

  roles:
    - { role: airtonix.provisioning/system/base, tags: ['base', 'system'] }
    - { role: airtonix.provisioning/system/python, tags: ['python', 'language', 'system'] }
    - { role: airtonix.provisioning/system/ruby, tags: ['ruby', 'language', 'system'] }
    - { role: airtonix.provisioning/system/nodejs-volta, tags: ['nodejs', 'language', 'system'] }
    - { role: airtonix.provisioning/system/docker, tags: ['docker', 'virtual', 'system'] }
    - { role: airtonix.provisioning/system/androiddev, tags: ['android', 'dev', 'system'] }
    - { role: airtonix.provisioning/system/flatpak, tags: ['flatpak', 'packages'] }
    - { role: airtonix.provisioning/apps/syncthing, tags: ['syncthing', 'sharing', 'desktop', 'apps'] }
    - { role: airtonix.provisioning/apps/kdeconnect, tags: ['kdeconnect', 'phone', 'desktop', 'apps'] }
    - { role: airtonix.provisioning/apps/docker, tags: ['docker', 'virtual', 'apps'] }
    - { role: airtonix.provisioning/apps/adb, tags: ['android', 'terminal', 'dev', 'apps'] }
    - { role: airtonix.provisioning/apps/tusk, tags: ['tusk', 'terminal', 'dev', 'apps'] }
    - { role: airtonix.provisioning/apps/go-task, tags: ['go-task', 'terminal', 'dev', 'apps'] }
    - { role: airtonix.provisioning/apps/shellspec, tags: ['shellspec', 'terminal', 'dev', 'apps'] }
    - { role: airtonix.provisioning/apps/git, tags: ['git', 'dev', 'vcs', 'terminal', 'apps'] }
    - { role: airtonix.provisioning/apps/mkdkr, tags: ['mkdkr', 'dev', 'ci', 'terminal', 'apps'] }
    - { role: airtonix.provisioning/apps/zsh, tags: ['dev', 'zsh', 'terminal', 'apps'] }
    - { role: airtonix.provisioning/apps/pass, tags: ['security', 'pass', 'terminal', 'apps'] }
    - { role: airtonix.provisioning/apps/ssh, tags: ['dev', 'ssh', 'terminal', 'apps'] }
    - { role: airtonix.provisioning/apps/sublime-text, tags: ['sublime', 'dev', 'ide', 'desktop', 'apps'] }
    - { role: airtonix.provisioning/apps/ms-vscode, tags: ['vscode', 'dev', 'ide', 'desktop', 'apps'] }
    - { role: airtonix.provisioning/apps/firefox, tags: ['browser', 'desktop', 'apps'] }
    - { role: airtonix.provisioning/apps/ms-teams, tags: ['chat', 'desktop', 'apps'] }
    - { role: airtonix.provisioning/apps/slack, tags: ['chat', 'desktop', 'apps'] }
    - { role: airtonix.provisioning/apps/steam, tags: ['steam', 'games', 'desktop', 'apps'] }
    - { role: airtonix.provisioning/apps/ledgerlive, tags: ['finance', 'desktop', 'apps'] }
    - { role: airtonix.provisioning/apps/mailspring, tags: ['email', 'desktop', 'apps'] }

  tasks:
    - name: install base packages
      package:
        state: present
        name:
          - yamllint
          - google-roboto-slab-fonts
          - htop
          - jq
          - powerline-fonts
          - youtube-dl
