---
- name: OSx Workstation configuration
  hosts: workstation
  become: true

  vars_prompt:
    - name: target_user
      prompt: What is your username?
      private: no
    - name: target_group
      prompt: What is your usergroup?
      private: no
    - name: target_user_name
      prompt: What is your full name?
      private: no

  vars:
    ansible_python_interpreter: /usr/bin/python3
    user_dir_home: /home/{{ target_user }}

  roles:
    - { role: airtonix.provisioning/system/nodejs }
    - { role: airtonix.provisioning/system/ansible }
