---
- name: Home Assistant Unitfile
  include_role:
    name: mhutter.docker-systemd-service
  vars:
    container_name: homeassistant
    container_image: linuxserver/homeassistant:latest
    container_args: --network=bridge
    container_env:
      TZ: Australia/Adelaide
    container_volumes:
      - '/yacht/AppData/Config/HomeAssistant/config:/config'
    container_ports:
      - '8123:8123'
    container_labels:
      - 'traefik.http.routers.home-assistant-router.rule=Host(`assistant.home.lan`)'
      - 'traefik.http.services.home-assistant-service.loadbalancer.server.port=8123'
      - 'traefik.http.routers.home-assistant-router.service=home-assistant-service'
